### ISSUE TITLE
Job Queue Library

### ISSUE THREAD

**Issue by sjarifHD** [AndroidDeveloperBandung/awesome-android-articles#10]
Alternatif library untuk background task di android.

Library:
https://github.com/yigit/android-priority-jobqueue

Sample:
https://solidgeargroup.com/android-priority-job-queue-background-tasks
https://github.com/yigit/dev-summit-architecture-demo

**Comment by esafirm** [comment]
@sjarifHD bagusnya under category apa ya? 
Job scheduling? Job Management? 

Ada masukan @derohimat @pratamawijaya ?

**Comment by sjarifHD** [comment]
Sepertinya Job scheduling

Pada tanggal 6 Agt 2017 16.20, "Esa Firman" <notifications@github.com>
menulis:

**Comment by pratamawijaya** [comment]
@esafirm @sjarifHD  **Job Scheduler**

**Comment by esafirm** [comment]
Added
