### ISSUE TITLE
Tutorial CRUD Rest API Menggunakan Retrofit 2 Android

### ISSUE THREAD

**Issue by farizdotid** [AndroidDeveloperBandung/awesome-android-articles#16]
https://farizdotid.com/tutorial-crud-rest-api-menggunakan-retrofit-2-android/

**Comment by esafirm** [comment]
Added 🎉 
I think the title is a little misleading so i put it as "Mengeksekusi CRUP REST API dengan Retrofit 2"

Just comment to this issue if you have better title 😁
