### ISSUE TITLE
Material Design

### ISSUE THREAD

**Issue by Danboru** [AndroidDeveloperBandung/awesome-android-articles#6]
https://developer.android.com/training/material/index.html
https://www.androidhive.info/category/material-design/
https://github.com/google/material-design-lite
https://www.materialpalette.com/
https://www.flaticon.com/

**Comment by esafirm** [comment]
I think the official training and Android Hive's can be accepted. Not sore about MDL though. 
The rest is more to a tools and not a learning material. 

Thanks for your contribution 🙏
